### ISSUE TITLE
Can this be packaged as a python package?

### ISSUE THREAD

**Issue by hwine** [imbal/safeyaml#16]
Well, sure it can -- the real question is are you open to that approach? :)

The advantages I see include:
- easier to install & update (even with pipsi)
- works on windows

Happy to do the first bit if you're open to the idea.

**Comment by aanand** [comment]
It's a bit of an experiment/prototype at the moment. If we did get to a point where we wanted to make it ready for others to use in earnest, we'd definitely publish it as a Python package - assuming that, at that point, it were still written in Python.

**Comment by hwine** [comment]
Thanks for the clarification on the status. I'll grab a fork after #17 is resolved.
